### ISSUE TITLE
Port Prompt:NumberWithUnitPrompt C# to Python

### ISSUE THREAD

**Issue by rvinothrajendran** [BotBuilderCommunity/botbuilder-community-python#1]
Hello @szul 

I have converted C# Prompt:NumberWithUnitPrompt class to Python class ,If that fine, will create PR and submit the code changes 

Regards & Thanks
Vinoth.

**Comment by szul** [comment]
@rvinothrajendran Yes. Feel free to submit a PR.

**Comment by rvinothrajendran** [comment]
thanks @szul , Kindly review the PR
